#!/usr/bin/python3
# SPDX-FileCopyRightText: 2023 Kazuki Noguchi
# SPDX-License-Identifire: BSD-3-Clause

import sys

ans1 = 0
ans2 = 1
i = 0
for line in sys.stdin:
    i += 1
    try:
        ans1 += int(line)
        ans2 *= int(line)
    except:
        ans1 += float(line)
        ans2 += float(line)

print(ans1)
print(ans1/int(i))
print(ans2)
